name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get short SHA
        id: short-sha
        run: echo "::set-output name=sha::$(git rev-parse --short $GITHUB_SHA)"

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: Build and push Docker image
        working-directory: .
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:${{ steps.short-sha.outputs.sha }}
        run: |
          docker build --network host -t "$IMAGE_NAME" .
          docker push $IMAGE_NAME

  deploy:
    needs: docker-build-and-push
    runs-on: self-hosted
    steps:
      - name: install kubectl
        uses: azure/setup-kubectl@v3
      - name: Update Deployment Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:${{ steps.short-sha.outputs.sha }}
        run: |
          kubectl set image deployment/${{ vars.SERVICE_NAME }} ${{ vars.SERVICE_NAME }}=$IMAGE_NAME -n services
