name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker-build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        working-directory: .
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker build --network host -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    needs: docker-build-and-push
    runs-on: self-hosted
    steps:
      - name: install kubectl
        uses: azure/setup-kubectl@v3
      - name: Update Deployment Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/sample-app:${{ github.sha }}
        run: |
          kubectl set image deployment/dataset-jobs-service dataset-jobs-service=$IMAGE_NAME -n services
